\input texinfo              @c -*-texinfo-*- 
 
@c %**start of header 
@setfilename DBusKit.info 
@settitle GNUstep D-Bus Programming Manual
@documentencoding UTF-8
@c %**end of header 
 
@ifinfo 
@format 
INFO-DIR-SECTION GNUstep 
START-INFO-DIR-ENTRY 
* DBusKit: (DBusKit).        DBusKit library and D-Bus Programming Manual
END-INFO-DIR-ENTRY 
@end format 
@end ifinfo 

@ifinfo
Copyright @copyright{} 2010--2014 Free Software Foundation

Permission is granted to copy, distribute and/or modify this
document under the terms of the GNU Free Documentation License,
Version 1.3 or any later version published by the Free Software
Foundation; with no Invariant Sections, no Front-Cover Texts and
no Back-Cover Texts.  A copy of the license is included in the
section entitled ``GNU Free Documentation License''.
@end ifinfo

@setchapternewpage odd
@titlepage

@title GNUstep
@title DBusKit and D-Bus
@title Programming Manual

@author Niels Grewe

@page
@vskip 0pt plus 1filll
Copyright @copyright{} 2010--2014 Free Software Foundation

Permission is granted to copy, distribute and/or modify this
document under the terms of the GNU Free Documentation License,
Version 1.3 or any later version published by the Free Software
Foundation; with no Invariant Sections, no Front-Cover Texts and
no Back-Cover Texts.  A copy of the license is included in the
section entitled ``GNU Free Documentation License''.
@end titlepage

@contents

@ifinfo
@node Top
@top GNUstep D-Bus Programming Manual
@menu
* Introduction::		  An introduction to the Distributed Objects and D-Bus IPC mechanisms
* Using D-Bus From Objective-C::  Describes how to access D-Bus services from an Objective-C application
* Exposing Objects on D-Bus::     Describes how to expose Objective-C objects to other D-Bus aware applications.
* GNU Free Documentation License::The license terms of this document
@end menu
@end ifinfo
@c Chapter 1: Introduction
@include Introduction.texi

@c Chapter 2: Using D-Bus From Objective-C
@include UsingDBus.texi

@c Chapter 3: Exposing Objects on D-Bus
@include ExposingObjects.texi

@c Appendix A: GNU Free Documentation License
@include fdl-1.3.texi

@unnumbered Concept Index
@printindex cp
@bye
