include $(GNUSTEP_MAKEFILES)/common.make

DOCUMENT_NAME = DBusKit

DBusKit_TEXI_FILES = 	DBusKit.texi \
			Introduction.texi \
			fdl-1.3.texi

AppKit_DOC_INSTALL_DIR = Developer/DBusKit/ProgrammingManual

include $(GNUSTEP_MAKEFILES)/documentation.make
